// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRWarSbckjuXWDiQZQ-zFKCcgaYFHiVnU',
    appId: '1:733804575642:web:116d36f8fa064cc2361823',
    messagingSenderId: '733804575642',
    projectId: 'geraeteverwaltung-4e8e6',
    authDomain: 'geraeteverwaltung-4e8e6.firebaseapp.com',
    storageBucket: 'geraeteverwaltung-4e8e6.firebasestorage.app',
    measurementId: 'G-ZEEVH2CG5V',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRWarSbckjuXWDiQZQ-zFKCcgaYFHiVnU',
    appId: '1:733804575642:web:116d36f8fa064cc2361823',
    messagingSenderId: '733804575642',
    projectId: 'geraeteverwaltung-4e8e6',
    authDomain: 'geraeteverwaltung-4e8e6.firebaseapp.com',
    storageBucket: 'geraeteverwaltung-4e8e6.firebasestorage.app',
    measurementId: 'G-ZEEVH2CG5V',
  );

}